# https://golangci-lint.run/usage/configuration/

issues:
  max-per-linter: 0
  max-same-issues: 0

run:
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    - exportloopref
    - forcetypeassert
    - godot
    - gofmt
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - tenv
    - unconvert
    - unparam
    - unused
    - vet
